### ISSUE TITLE
feature request: one more hub endpoint to cache

### ISSUE THREAD

**Issue by clockworkgr** [EmerisHQ/demeris-api-server#6]
RIght now we're serving cached copies of : 

/cosmos/liquidity/v1beta1/pools
/cosmos/liquidity/v1beta1/params
/cosmos//bank/v1beta1/supply

https://github.com/allinbits/demeris-api-server/blob/main/api/cached/api.go

Can we also add the standard `/node_info` endpoint to `cached` as well ?

**Comment by gsora** [comment]
Yup, feasible.

@sgerogia can we schedule this?

**Comment by clockworkgr** [comment]
@sgerogia @gsora status?

**Comment by sgerogia** [comment]
@clockworkgr will be picked up on Mon 10 Jan

**Comment by sahith-narahari** [comment]
If this is being worked on, Alex reported there's a type mismatch between cached responses and grpc responses from sdk.
We need to look into it, most probably related to how we're reading data from cache

**Comment by gsora** [comment]
We're caching whatever `codec.MarshalJSON()` is returning us, I'm expecting this to be _the_ correct encoding.

What's encoded wrong?

**Comment by clockworkgr** [comment]
@gsora  if accessing the api directly, uint64/int64s are correctly sent as strings in the JSON as per proto-> json specs

If accessing the cached version, uint64/int64s are sent as numbers

**Comment by gsora** [comment]
Just tried locally with a Gaia v6 node, SDK 0.44.5 codec, this is the result:

```json
{
  "supply": [
    {
      "denom": "stake",
      "amount": "1100279048"
    },
    {
      "denom": "validatortoken",
      "amount": "1000000000"
    }
  ],
  "pagination": {
    "next_key": null,
    "total": "2"
  }
}
```

The issue lies in `api-server`, because:
1. `rpcwatcher` stores the supply as the JSON bytes marshaled with Cosmos's `codec.MarshalJSON`
2. `api-server` retrieves those bytes, _unmarshals them back into their Cosmos types_ and then _marshals them with the Go's `encoding/json` marshaler_, and this is where the bug happens.

The simple fix here is to simply get rid of whatever marshaling/unmarshaling magic `api-server` is doing, and simply return JSON bytes as taken from `rpcwatcher` cached data.

For example, `emeris-utils/store.GetSupply()` should be refactored like this:

```go
func (s *Store) GetSupply() ([]byte, error) {
	bz, err := s.Client.Get(context.Background(), "supply").Bytes()
	if err != nil {
		return nil, fmt.Errorf("cannot fetch cached supply, %w")
	}

	return bz, nil
}
```

Anybody willing to do this?

**Comment by 0xbala-k** [comment]
On it!!!

**Comment by gsora** [comment]
@SpideyPool192 please target the PR on `api-server` on `main`, so we can backport it easily if needed.

**Comment by sahith-narahari** [comment]
@SpideyPool192 can we close this?

**Comment by 0xbala-k** [comment]
Yup. This is done.
